development: &dev
  linkshare:
    storage_method: cache
    s3_bucket:
    name: 'linkshare-atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://localhost:3000/linkshare-atom.xml
  polyvor:
    storage_method: cache
    s3_bucket:
    name: 'polyvor_feed.tsv'
    host:  http://www.woolandthegang.com
    feed_url: http://localhost:3000/polyvor.tsv
 
    
test:
  <<: *dev

staging: &staging
  linkshare:
    storage_method: s3
    s3_bucket: feeds.watg-staging.com
    name: 'linkshare/atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://s3.amazonaws.com/feeds.watg-staging.com/linkshare/atom.xml
  polyvor:
    storage_method: s3
    s3_bucket: feeds.watg-staging.com
    name: 'polyvor/feed.tsv'
    host:  http://www.woolandthegang.com
    feed_url: http://s3.amazonaws.com/feeds.watg-staging.com/polyvor/feed.tsv

production:
  linkshare:
    storage_method: s3
    s3_bucket: feeds.woolandthegang.com  ## items in that bucket have to be publicly accessible
    name: 'linkshare/atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://feeds.woolandthegang.com/linkshare/atom.xml
  polyvor:
    storage_method: s3
    s3_bucket: feeds.woolandthegang.com  ## items in that bucket have to be publicly accessible
    name: 'polyvor/feed.tsv'
    host:  http://www.woolandthegang.com
    feed_url: http://feeds.woolandthegang.com/polyvor/feed.tsv
