development: &dev
  linkshare:
    storage_method: cache
    s3_bucket: 
    name: 'linkshare-atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://localhost:3000/linkshare-atom.xml
    
test:
  <<: *dev

staging: &staging
  linkshare:
    storage_method: s3
    s3_bucket: watg-dest-test
    name: 'linkshare/atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://s3.amazonaws.com/watg-dest-test/linkshare/atom.xml

production:
  linkshare:
    storage_method: s3
    s3_bucket: feeds.woolandthegang.com  ## items in that bucket have to be publicly accessible
    name: 'linkshare/atom.xml'
    host:  http://www.woolandthegang.com
    feed_url: http://feeds.woolandthegang.com/linkshare/atom.xml
